services:
  gate:
    image: golang:1.23.5
    restart: unless-stopped
    working_dir: /gate/example
    command: [ "go", "run", "main.go", "-c", "gate.yml" ]
    environment:
      - GEYSER_LISTEN_ADDR=:25566
    volumes:
      - ../:/gate
      - ./geyser/key.pem:/etc/gate/floodgate.pem
    ports:
      - "25565:25565"
  geyser:
    image: itzg/minecraft-server
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: "CUSTOM"
      CUSTOM_SERVER: "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/standalone"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./geyser/config.yml:/data/config.yml
      - ./geyser/key.pem:/data/key.pem
  server1:
    image: itzg/minecraft-server
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.21.4
      PAPER_BUILD: 133
      PLUGINS: |
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      EXTRA_ARGS: "--world-dir ./worlds/"
    volumes:
      - worlds:/worlds
      - ./server1/server.properties:/data/server.properties
      - ./server1/config:/data/config
      - ./geyser/floodgate.yml:/data/plugins/floodgate/config.yml
      - ./geyser/key.pem:/data/plugins/floodgate/key.pem
volumes:
  worlds:
