services:
  gate:
    container_name: gate
    image: golang:1.23.5
    restart: unless-stopped
    working_dir: /gate/example
    command: [ "go", "run", "main.go", "-c", "gate.yml" ]
    volumes:
      - ../:/gate
    ports:
      - "25565:25565"
    networks:
      mc:
        ipv4_address: 172.30.1.2
  geyser:
    container_name: geyser
    image: itzg/minecraft-server
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: "CUSTOM"
      CUSTOM_SERVER: "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/standalone"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./geyser/config.yml:/data/config.yml
      - ./geyser/key.pem:/data/key.pem
    networks:
      mc:
        ipv4_address: 172.30.1.3
  server1:
    container_name: server1
    image: itzg/minecraft-server
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.21.4
      PAPER_BUILD: 133
      PLUGINS: |
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      EXTRA_ARGS: "--world-dir ./worlds/"
    volumes:
      - worlds:/worlds
      - ./server1/server.properties:/data/server.properties
      - ./server1/config:/data/config
      - ./geyser/floodgate.yml:/data/plugins/floodgate/config.yml
      - ./geyser/key.pem:/data/plugins/floodgate/key.pem
    networks:
      mc:
        ipv4_address: 172.30.1.4
networks:
  mc:
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
volumes:
  worlds:
